config/routes.rb
Seo::Application.routes.draw do

  scope "/:locale" do

    resources :home
    resources :how_it_works
    resources :faq
    resources :partners
    resources :about_us
    resources :signup, :except => :index
    resources :privacy_policy
    resources :terms_of_service
    root :to => "home#index"

    match '/:locale/how_it_works' => 'how_it_works#index', :as => 'how_it_works', :via => :get, :path => 'how-it-works'
    match '/:locale/faq' => 'faq#index', :as => 'faq', :via => :get, :path => 'faq'
    match '/:locale/partners' => 'partners#index', :as => 'partners', :via => :get, :path => 'partners'
    match '/:locale/about' => 'about#index', :as => 'about', :via => :get, :path => 'about'
    match '/:locale/signup' => 'signup#new', :as => 'signup', :via => :get, :path => 'signup'
    match '/:locale/signup' => 'signup#create', :as => 'signup', :via => :post, :path => 'signup'
    match '/:locale/privacy_policy' => 'privacy_policy#index', :as => 'privacy_policy', :via => :get, :path => 'privacy-policy'
    match '/:locale/terms_of_service' => 'terms_of_service#index', :as => 'terms_of_service', :via => :get, :path => 'terms-of-service'

  end

  root :to => "home#index"

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone, :website

  validates :name, :email, :phone, :website, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    [*attributes].each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  ##### for internationalization
  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end


  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end
  #####

end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/how_it_works_controller.rb
class HowItWorksController < ApplicationController
  def index
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
  end
end

app/controllers/privacy_policy_controller.rb
class PrivacyPolicyController < ApplicationController

  def index
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(signup_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/terms_of_service_controller.rb
class TermsOfServiceController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/how_it_works_helper.rb
module HowItWorksHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/privacy_policy_helper.rb
module PrivacyPolicyHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/terms_of_service_helper.rb
module TermsOfServiceHelper
end

app/views/about/index.html.erb
<% content_for :head do %>
    <title><%= t('about.title', :default=> 'About SEO Marketing') %></title>
<% end %>
<div id="content-main" class="pages">

  <!--
  <h1>About SEOMarketing</h1>
  <div class="odd">
    <p>SEOMarketing Co., Ltd. is full service Internet Marketing company that provides Pay-For-Results Search Engine Optimization (SEO) services to companies around the world. Our Marketing Operations Center is located in Bangkok, Thailand.</p>
  </div>
  <h2>Our SEO Philosophy</h2>
  <div class="even">
    <h3>Customers Pay Only For Results</h3>
    <p>We believe customer should only have to pay for results. With our Pay-For-Result SEO service the customer is assured our Marketing Operations Team is 100% motivated to get our customer's ranked as fast as possible.</p>
    <h3>Continuous Improvement</h3>
    <p>Month after month we write articles, submit links, and promote our customer's website on social media sites such as Facebook and Twitter that drive traffic and improve our customer's SEO rankings.</p>
    <h3>The Search Engines' Best Friend</h3>
    <p>We are committed to using search engine friendly marketing methods rooted in sound marketing principles. This helps insure that our customers keep, and even improve, their SEO rankings over time.</p>
  </div>
  -->
  <%= t('about.page') %>

</div>

app/views/faq/index.html.erb
<% content_for :head do %>
    <title><%= t('faq.title', :default=> 'SEO Marketing FAQ') %></title>
<% end %>
<div id="content-main" class="pages">

  <!--
  <h1>SEOMarketing FAQs</h1>
  <br><br>
  <h2>What is the Free SEO Analysis?</h2>
  <div class="odd">
    The free SEO report helps customers focus their online marketing strategy on achievable goals. The report includes on-page optimization suggestions, a competitive analysis, and our analyst's expert keyword suggestions with difficulty scores and traffic estimates. It's all the data we need to calculate our Pay-For-Results rate card, and we share all the data with you absolutely free with no obligation.
  </div>
  <h2>How does SEOMarketing Make Money?</h2>
  <div class="even">
    We get paid for the Search Engine Result Page (SERP) rankings results we help our customers achieve.
  </div>
  <h2>How does Pay-For-Result (PFR) SEO Pricing Work?</h2>
  <div class="odd">
    During the free SEO Analysis we prepare a rate card for the top 30 SERP results on Google and Yahoo/Bing. The prices on the rate card reflects the keyword's popularity and value relative to our customer's competitive strengths.
  </div>
  <h2>How do I get billed?</h2>
  <div class="even">
    We track your SERP rankings over a 30 day period and calculate your average ranking for the month.  We then apply the rate card when creating your invoice.
  </div>
  <h2>What if I'm already in the top 30 SERP Rankings.</h2>
  <div class="odd">
    You only pay for the rankings we help you improve.  if your rankings do not improve you will not be invoiced for our services.
  </div>
  -->
  <%= t('faq.page') %>

</div>

app/views/home/index.html.erb
<% content_for :head do %>
    <title><%= t('home.title', :default=> 'SEO Marketing - get the results you want') %></title>
<% end %>
<div id="content-main">
  <div id="banner-home">
    <a href="/"><%= image_tag("rank-banner-chart.png", :alt => "SEOMarketing - rank before you pay!", :id => "logo") %></a>
  </div>
  <div id="content-bottom-home">

    <!--<div id="bottom-left-home">
      <h1>SEO You Can Trust!</h1>
      <p>SEOMarketing's Search Engine Optimization service gets your ranked before you pay. Learn how our Pay-For-Results search marketing service works, or get started with a FREE SEO review.</p>
    </div>-->
    <%= t('home.bottom_left') %>

    <!--<div id="bottom-right-home">
      <h2>FREE SEO MARKETING ANALYSIS</h2>
      <p>Signup to have an SEO Analysist review your website and learn how SEOMarketing can increase your Search Engine rankings.</p>
      <div class="center-it"><%= link_to 'Sign Up Now', ['signup', @signup], :class => "button orange glossy" %></div>
    </div>-->
    <%= t('home.bottom_right') %>

  </div>
</div>

app/views/how_it_works/index.html.erb
<% content_for :head do %>
    <title><%= t('how_it_works.title', :default=> 'How It Works - SEO Marketing') %></title>
<% end %>
<div id="content-main" class="pages">

  <!--
  <h1>How It Works</h1>
  <div id="how-it-works">
      <ul>
        <li>We start with a Free SEO Marketing Analysis which includes our expert keyword suggestions.</li>
        <li>Included with your free SEO report is a rate card for the top 30 organic search results.</li>
        <li>When you are ready to begin, simply return the agreement and SEOMarketing begins to optimize your web site and market your business online.</li>
        <li>Every 30 days you get a detailed Search Engine Results Page (SERP) rankings report with the results. You pay only for the search engine rankings we helped you achieve.</li>
      </ul>
    <hr>
  </div>
  -->
  <%= t('how_it_works.how_it_works') %>

  <div id="rank-before-you-pay">
    <h2>Rank Before You Pay</h2>
    <div id="satisfaction-guarantee"><%= image_tag("satisfaction-guarantee-w150-h150.png", :alt => "SEOMarketing - Satisfaction Guarantee") %> </div>
    <h6 style="text-align: center;margin-bottom: 40px;">100% Satisfaction Guaranteed</h6>
    <hr>
  </div>

  <!--
  <h2>Features and Benefits</h2>
  <div id="features-benefits">
    <ul>
      <li class="pay-for-result"><h5>Pay-For-Result</h5>Only pay for the rankings we help you achieve.</li>
      <li class="satisfaction-guaranteed"><h5>Satisfaction 100% Guaranteed</h5>If you're not satisfied, simply contact us so we can work with you to make it right.</li>
      <li class="dedicated-seo-expert"><h5>Dedicated SEO Expert</h5>Your dedicated SEO marketing expert will take time to understand your business and find solutions to your online marketing needs.</li>
      <li class="keyword-research"><h5>Keyword Research</h5>Using a sophisticated set of tools, we help you pick the right keywords for your marketing goals.</li>
      <li class="page-optimization"><h5>Page Optimization</h5>On the first day, our SEO team thoroughly reviews and optimizes more than 150 search engine ranking factors on your website.</li>
      <li class="website-monitoring"><h5>Website Monitoring</h5>Our Marketing Operations Center continuously monitors changes to hundreds of SEO Ranking Factors and updates your web pages with the correct response.</li>
      <li class="site-map-management"><h5>Site Map Management</h5>We monitor changes to your website to ensure that all the major search engines have a current and complete copy of your sitemap.</li>
      <li class="link-building"><h5>Link Building</h5>Our Marketing Operations Center continuously scours the web for linking opportunities. Our SEO experts then manually submit your website to the high quality websites they find that are a good fit for your business.</li>
      <li class="content-development"><h5>Content Development</h5>Our expert copywriters will help you write keyword rich product descriptions, press releases, blog content and more.</li>
      <li class="social-media-marketing"><h5>Social Media Marketing</h5>Our online marketing team will help you craft the perfect social media marketing campaign and regularly post updates to sites like Facebook and Twitter.</li>
      <li class="consistent-reporting"><h5>Consistent Reporting</h5>You can track your progress with regular reports sent to your email.</li>
      <li class="geo-targeted"><h5>GEO Targeted</h5>We target your SEO campaigns to the country you want to market.</li>
    </ul>
  </div>
  -->
  <%= t('how_it_works.features_and_benefits') %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top">
  <nav id="container-top">

    <% if I18n.locale == I18n.default_locale %>
        <%= link_to(image_tag("seomarketing-logo.png", :alt => "SEOMarketing - get the results you want", :id => "logo"), '/' ) %>
    <% else %>
        <%= link_to(image_tag("seomarketing-logo.png", :alt => "SEOMarketing - get the results you want", :id => "logo"), 'home' ) %>
    <%end%>

    <ul id="nav-top">
      <li><%= link_to_unless_current t('header_nav.how_it_works', :default=> 'How It Works'), ['how_it_works', @how_it_works] do link_to t('header_nav.how_it_works', :default=> 'How It Works'), how_it_works_path, :class => "current" end %></li>
      <li><%= link_to_unless_current t('header_nav.faq', :default=> 'FAQ'), ['faq', @faq]  do link_to t('header_nav.faq', :default=> 'FAQ'), 'faq', :class => "current" end %></li>
      <li><%= link_to_unless_current t('header_nav.partners', :default=> 'Partners'), ['partners', @partners_index] do link_to t('header_nav.partners', :default=> 'Partners'), 'partners', :class => "current" end %></li>
      <li><%= link_to_unless_current t('header_nav.about', :default=> 'About'), ['about', @about_us] do link_to t('header_nav.about', :default=> 'About'), 'about', :class => "current" end %></li>
      <li><%= link_to_unless_current t('header_nav.signup', :default=> 'Signup'), ['signup', @signup], :class => "nav-top-signup" do link_to t('header_nav.signup', :default=> 'Signup'), 'signup', :class => "signup-current" end %></li>
    </ul>
  </nav>
</div>
<div id="container-main">
  <div id="nav-right">
    <div id="language-choice">

      <!--<% if I18n.locale == I18n.default_locale %>
              <%= link_to 'EN', url_for( :locale => 'en' ), :id => 'en' %>
          <% else %>
              <%= link_to 'TH', url_for( :locale => 'th' ), :id => 'th' %>
          <%end%>-->

      <%= link_to 'TH', url_for( :locale => 'th' ), :id => 'th', :class => 'language-current' %> | <%= link_to 'EN', url_for( :locale => 'en' ), :id => 'en' %></div>
  </div>

  <%= yield %>

</div>

<footer>
  <ul id="nav-footer">
    <li>&copy; Copyright <%= Time.now.year %> SEOMarketing.co.th</li>
    <li><%= link_to t('footer_nav.privacy_policy', :default=> 'Privacy Policy'), ['privacy_policy', @privacy_policy] %></li>
    <li><%= link_to t('footer_nav.terms_of_service', :default=> 'Terms of Service'), ['terms_of_service', @terms_of_service] %></li>
  </ul>
  <div id="social-icons">
    <a href="#" class="social-icon-facebook"></a>
    <a href="#" class="social-icon-twitter"></a>
  </div>
</footer>


</body>
</html>

app/views/partners/index.html.erb
<% content_for :head do %>
    <title><%= t('partners.title', :default=> 'Partners of SEO Marketing') %></title>
<% end %>
<div id="content-main" class="pages">

  <!--
  <h1>Featured Partners</h1>
  <div id="featured-partners">
    <ul>
        <li><a href="http://www.siaminterhost.com"><%= image_tag("logo_siaminter.gif", :alt => "SiamInterhost - Thailand's leading web host provider", :id => "logo-featured-partner") %></a><strong>SiamInterhost</strong> - Thailand's leading web host provider which offers Web Hosting plans that include 24/7/365 support and 99.9% uptime. SiamInterhost is proud to offer SEOMarketing.co.th, accessible in the Control Panel, to all our customers.</li>
    </ul>
  </div>
  -->

  <%= t('partners.page') %>
</div>

app/views/privacy_policy/index.html.erb
<% content_for :head do %>
    <title>SEOMarketing's Privacy Policy</title>
<% end %>
<div id="content-main" class="pages privacy-policy">
  <h1>Our Privacy Policy</h1>
  <p>This Privacy Policy governs the manner in which SEOMarketing Co., Ltd.  collects, uses, maintains and discloses information collected from users (each, a "User") of the seomarketing.co.th website ("Site"). This privacy policy applies to the Site and all products and services offered by SEOMarketing Co., Ltd. .</p>

  <h5>Personal identification information</h5>

  <p>We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, subscribe to the newsletter, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, mailing address, phone number. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>

  <h5>Non-personal identification information</h5>

  <p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>

  <h5>Web browser cookies</h5>

  <p>Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>

  <h5>How we use collected information</h5>

  <p>SEOMarketing Co., Ltd.  may collect and use Users personal information for the following purposes:</p>

  <h6>To improve customer service</h6>
  <p>Information you provide helps us respond to your customer service requests and support needs more efficiently.</p>
  <h6>To personalize user experience</h6>
  <p>We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</p>
  <h6>To improve our Site</h6>
  <p>We may use feedback you provide to improve our products and services.</p>
  <h6>To process payments</h6>
  <p>We may use the information Users provide about themselves when placing an order only to provide service to that order. We do not share this information with outside parties except to the extent necessary to provide the service.</p>
  <h6>To run a promotion, contest, survey or other Site feature</h6>
  <p>To send Users information they agreed to receive about topics we think will be of interest to them.</p>
  <h6>To send periodic emails</h6>
  <p>We may use the email address to send User information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests. If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</p>

  <h5>How we protect your information</h5>

  <p>We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p>

  <p>Sensitive and private data exchange between the Site and its Users happens over a SSL secured communication channel and is encrypted and protected with digital signatures.</p>

  <h5>Sharing your personal information</h5>

  <p>We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.We may use third party service providers to help us operate our business and the Site or administer activities on our behalf, such as sending out newsletters or surveys. We may share your information with these third parties for those limited purposes provided that you have given us your permission.</p>

  <h5>Third party websites</h5>

  <p>Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website's own terms and policies.</p>

  <h5>Compliance with children's online privacy protection act</h5>

  <p>Protecting the privacy of the very young is especially important. For that reason, we never collect or maintain information at our Site from those we actually know are under 13, and no part of our website is structured to attract anyone under 13.</p>

  <h5>Changes to this privacy policy</h5>

  <p>SEOMarketing Co., Ltd.  has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</p>

  <h5>Your acceptance of these terms</h5>

  <p>By using this Site, you signify your acceptance of this policy and terms of service. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p>

  <h6>Contacting us</h6>

  <p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:<br><br>

  <%= link_to 'SEOMarketing.com', "/"%><br>
  SEOMarketing Co., Ltd.<br>
  1518/5 Floor 4, CeaShun Building<br>
  Phacharaj 1 Rd.<br>
  Wongsawang, Bungsue<br>
  Bangkok 10800<br>
  Thailand<br>
  john@webexperts.co.th</p>

  <p>This document was last updated on July 12, 2012</p>

</div>

app/views/signup/new.html.erb
<% content_for :head do %>
    <title><%= t('signup.title', :default=> 'Sign up for SEO Marketing') %></title>
<% end %>

<div id="content-main" class="pages">

  <!--
  <h1>SignUp</h1>
  <div id="get-started">
    <ul>
      <li>Learn 5 things we can do today to improve your SEO results</li>
      <li>Get specific keyword suggestions and pricing information from a dedicated SEO expert</li>
      <li>Receive a free digital copy of our SEO Ranking Factors Report</li>
    </ul>
  </div>
  -->
  <%= t('signup.signup') %>

  <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <div id="contact-form" class="clearfix">

    <!--
    <h3>Get SEO Optimized!</h3>
    <h4>Fill out the contact form below and we will get back to you very soon</h4>
    <ul id="errors" class="">
      <li id="info">There were some problems with your form submission:</li>
    </ul>
    <p id="success">Thanks for your message! We will get back to you ASAP!</p>
    -->
    <%= t('.form.call_to_action') %>

<%= form_for @message, :url => signup_path do |form| %>
    <fieldset class="fields">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, :id => "name", :placeholder => "John Doe", :required => "required", :autofocus => "autofocus"%>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email, :type => "email", :id => "email", :placeholder => "johndoe@example.com", :required => "required" %>
      </div>
      <div class="field">
        <%= form.label :phone %>
        <%= form.text_field :phone, :placeholder => "0805555555", :required => "required" %>
      </div>

      <div class="field">
        <%= form.label :website %>
        <%= form.text_field :website, :id => "website", :placeholder => "your-domain-here.co.th", :'data-minlength' => "5", :required => "required" %>
      </div>
    </fieldset>

    <fieldset class="actions">
      <%= form.submit "Send", :id => 'submit-button'%>
    </fieldset>
    <p id="req-field-desc"><span class="required">*</span> indicates a required field</p>
<% end %>

  </div>
</div>